<h1>Articles creation page</h1>

<form action="<?php echo $block->getUrl('blog/create/savepost') ?>" method="post">
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Articles Fill Details')) ?></span></legend>
        <fieldset class="fieldset row">
            <div class="fields col-md-6">
                <div class="field name required">
                    <label class="label" for="title"><span><?= $block->
                            escapeHtmlAttr(__('Author')) ?></span></label>
                    <div class="control">
                        <input name="author" id="author" title="Author" value="" class="input-text" type="text"
                               data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                    </div>
                </div>
                <div class="field name ">
                    <label class="label" for="title"><span><?= $block->
                            escapeHtmlAttr(__('Article Title')) ?></span></label>
                    <div class="control">
                        <input name="title" id="title" title="<?= $block->escapeHtmlAttr(__('Enter your article Title here')) ?>" value="" class="input-text" type="text"
                               data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                    </div>
                </div>
                <div class="field name ">
                    <label class="label" for="title"><span><?= $block->
                            escapeHtmlAttr(__('Article Text:')) ?></span></label>
                    <div class="control">
                        <textarea name="body"
                                  id="body"
                                  title="<?= $block->escapeHtmlAttr(__('Enter your article text here')) ?>"
                                  class="input-text"
                                  cols="5"
                                  rows="4"
                                  data-validate="{required:true}"
                        >
                        </textarea>
                    </div>
                </div>
                <div class="field name ">
                    <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Date of creation')) ?></span></label>
                    <div class="control">
                        <input name="created_at" id="created_at" title="Date of creation" value="" class="input-text"
                               type="date" data-validate="{required:true}">
                    </div>
                </div>
            </div>
        </fieldset>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="Save"><span><?= $block->
                    escapeHtmlAttr(__('Publish your article')) ?></span></button>
        </div>
    </div>
</form>
