<?php
/** @var Magento\Framework\View\Element\Template $block */
?>

<h2>Welcome to Blogs</h2>

<?php $postViewModel = $block->getData('view_model'); ?>
<?php $posts = $postViewModel ? $postViewModel -> getList() : []; ?>

<?php if (empty($posts)) : ?>
    <div><?= __('No available posts'); ?></div>
<?php else : ?>
    <?php foreach ($posts as $post) : ?>
        <div>
            <a href="<?= $block->getUrl('blog/post/view/id/' . $post->getId()); ?>">
                <?= $post->getTitle(); ?>
            </a><span>written by: <?=  $post->getAuthor(); ?></span>
        </div>
    <?php endforeach;?>
<?php endif; ?>

<button id="click_me" class="theme_button"><?= __('Click Me'); ?></button>

<script type="text/x-magento-init">
    {
        "*" : {
            "Shkil_Blogposts/js/clickme" : {
                "ajaxUrl" : "<?php echo $block->getUrl('blog/ajax/clickme'); ?>"
            }
        }
    }
</script>
